-- boos 시퀀스 생성
CREATE SEQUENCE BOOK_SEQ;

-- boos table 생성
CREATE TABLE BOOKS
(					
	BOOK_NUM NUMBER PRIMARY KEY,								
	NAME VARCHAR2(20) NOT NULL,			
	TITLE VARCHAR2(50) NOT NULL,				
	CONTENT VARCHAR2(2000) NOT NULL												
);	