**StudyRoom DB관련 //
// 20170821 TEST용 테이블 임시 생성
=======
-- StudyRoom DB관련
-- 20170821 TEST용 테이블 임시 생성
>>>>>>> branch 'master' of https://github.com/SESmanagement/SESmanagement.git

CREATE TABLE STUDYROOM
(
	STUDYROOM_NUM NUMBER NOT NULL,
	SR_SEAT_NUM NUMBER NOT NULL,
	RECHARGABLE VARCHAR2(5) DEFAULT 'N',
	SEATED_STATUS NUMBER DEFAULT 0,
	ROOM_X NUMBER NOT NULL,
	ROOM_Y NUMBER NOT NULL,
	SEAT_X NUMBER NOT NULL,
	SEAT_Y NUMBER NOT NULL,
	CONSTRAINT STUDYROOM_PK PRIMARY KEY(STUDYROOM_NUM, SR_SEAT_NUM)
);

//StyduRoom 더미데이터
INSERT INTO STUDYROOM VALUES(1, 1, 'N', 0);
INSERT INTO STUDYROOM VALUES(1, 2, 'N', 0);
INSERT INTO STUDYROOM VALUES(1, 3, 'Y', 0);
INSERT INTO STUDYROOM VALUES(1, 4, 'Y', 0);
INSERT INTO STUDYROOM VALUES(2, 1, 'Y', 0);
INSERT INTO STUDYROOM VALUES(2, 2, 'Y', 0);
INSERT INTO STUDYROOM VALUES(2, 3, 'Y', 0);
INSERT INTO STUDYROOM VALUES(2, 4, 'Y', 0);

**StudyRoom Reservation DB관련
// 20170824 TEST용 테이블 임시 생성 (학생번호 추가)
CREATE TABLE SR_RESERVATION	
(	
	SR_RESV_NUM VARCHAR2(10) PRIMARY KEY,
	STUDYROOM_NUM NUMBER NOT NULL, 
	SR_SEAT_NUM NUMBER NOT NULL,
	STUDENT_NUM NUMBER REFERENCES MEMBER(STUDENT_NUM) NOT NULL,
	START_TIME TIMESTAMP NOT NULL,
	END_TIME TIMESTAMP NOT NULL
);

// 2017-09-01 SR_RESERVATION 테이블의 페이크 데이터 - 테이블 EMPTY 방지
INSERT INTO SR_RESERVATION VALUES (
'SRR000', 1, 1, 1, '70-01-01 00:00:00', '70-01-01 00:00:00');

// SR_RESV_NUM의 시퀀스 생성 (예약일련번호 : "SRR"+SRR_SEQ.NEXTVAL)
CREATE SEQUENCE SRR_SEQ;

// 2017-09-05 SR_FACILITY 테이블 생성 (문, 칠판, 콘센트 등 스터디룸 부가시설 표시)
CREATE TABLE SR_FACILITY (
  STUDYROOM_NUM NUMBER NOT NULL,
  FACILITY_NUMBER NUMBER DEFAULT 0,
  FACILITY_NAME VARCHAR2(50),
  SEAT_X NUMBER NOT NULL,
  SEAT_Y NUMBER NOT NULL,
  ACTIVATE NUMBER DEFAULT 1 NOT NULL
  );

// 2017-09-20 EVENT 테이블 생성 (스케줄링)
CREATE TABLE EVENT (
  STUDENT_NUM NUMBER REFERENCES MEMBER(STUDENT_NUM),
  MEMO VARCHAR2(50),
  ID VARCHAR2(50) PRIMARY KEY,
  TITLE VARCHAR2(50) NOT NULL,
  ALLDAY NUMBER(1),
  START_TIME TIMESTAMP NOT NULL,
  END_TIME TIMESTAMP NOT NULL,
  URL_STR VARCHAR2(100),
  CLASSNAME VARCHAR2(100),
  EDITABLE NUMBER(1),
  STARTEDITABLE NUMBER(1),
  DURATIONEDITABLE NUMBER(1),
  RESOURCEEDITABLE NUMBER(1),
  RENDERING VARCHAR2(50),
  OVERLAP NUMBER(1),
  CONSTRAINT_EVENT NUMBER(1),
  SOURCE_EVENT VARCHAR2(50),
  BACKGROUNDCOLOR VARCHAR2(50),
  BORDERCOLOR VARCHAR2(50),
  TEXTCOLOR VARCHAR2(50)
);

// 스케줄링의 ID의 시퀀스 생성 (이벤트일련번호 : "EV"+EV_SEQ.NEXTVAL)
CREATE SEQUENCE EV_SEQ;